services:
  hz1:
    image: hazelcast/hazelcast:5.4
    container_name: hz1
    hostname: hz1
    ports: ["5701:5701"]
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml:ro

  hz2:
    image: hazelcast/hazelcast:5.4
    container_name: hz2
    hostname: hz2
    ports: ["5702:5701"]
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml:ro

  hz3:
    image: hazelcast/hazelcast:5.4
    container_name: hz3
    hostname: hz3
    ports: ["5703:5701"]
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml:ro
