services:
  db:
    image: postgres:16-alpine
    container_name: pg-counter-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: counterdb
    ports:
      - "5432:5432"
    volumes:
      - pg_counter_data:/var/lib/postgresql/data
volumes:
  pg_counter_data:
